// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBroQle4xePi4ax7H-to8nHhcTvxvs32jE',
    appId: '1:83950753417:web:f98ec5fb6a803833675858',
    messagingSenderId: '83950753417',
    projectId: 'inventory-app-safia',
    authDomain: 'inventory-app-safia.firebaseapp.com',
    storageBucket: 'inventory-app-safia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpA4-H4983uWegCMFp5lTlKVACLCQY1qc',
    appId: '1:83950753417:android:cb7f1f3ee1f18e70675858',
    messagingSenderId: '83950753417',
    projectId: 'inventory-app-safia',
    storageBucket: 'inventory-app-safia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr6aJpGabtp6V8RyKzmEcK5-wi9kbCmcc',
    appId: '1:83950753417:ios:b8f183bb669599a9675858',
    messagingSenderId: '83950753417',
    projectId: 'inventory-app-safia',
    storageBucket: 'inventory-app-safia.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr6aJpGabtp6V8RyKzmEcK5-wi9kbCmcc',
    appId: '1:83950753417:ios:b8f183bb669599a9675858',
    messagingSenderId: '83950753417',
    projectId: 'inventory-app-safia',
    storageBucket: 'inventory-app-safia.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBroQle4xePi4ax7H-to8nHhcTvxvs32jE',
    appId: '1:83950753417:web:b319838cdb3c9488675858',
    messagingSenderId: '83950753417',
    projectId: 'inventory-app-safia',
    authDomain: 'inventory-app-safia.firebaseapp.com',
    storageBucket: 'inventory-app-safia.firebasestorage.app',
  );

}